### ISSUE TITLE
I'm having an issue when I try queuing music with NuclearMusic. [FATAL] Could not pass event "cn.nukkit.event.player.PlayerInteractEvent" to "NuclearMusic v1.2.0": null on com.fcmcpe.nuclear.music.NuclearMusicPlugin$NuclearMusicListener

### ISSUE THREAD

**Issue by SilentBlade1472** [PetteriM1/NuclearMusic#2]
16:38:06 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerInteractEvent" to "NuclearMusic v1.2.0": null on com.fcmcpe.nuclear.music.NuclearMusicPlugin$NuclearMusicListener
16:38:06 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[server.jar:?]
at cn.nukkit.level.Level.useItemOn(Level.java:2052) ~[server.jar:?]
at cn.nukkit.level.Level.useItemOn(Level.java:2020) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:3045) ~[server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at cn.nukkit.network.Network.processPackets(Network.java:197) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:180) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2105) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [server.jar:?]
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [server.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [server.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:83) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1132) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:911) [server.jar:?]
at cn.nukkit.Server.start(Server.java:888) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:573) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.util.NoSuchElementException
at java.util.LinkedList.getFirst(LinkedList.java:244) ~[?:1.8.0_242]
at com.fcmcpe.nuclear.music.NuclearMusicPlugin$NuclearMusicListener.onBlockTouch(NuclearMusicPlugin.java:120) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
... 20 more

**Comment by PetteriM1** [comment]
It looks like you are trying to set up a noteblock player but you don't have any songs loaded

**Comment by SilentBlade1472** [comment]
I have a .nbs loaded in the folder though... I even regenerated the folder when It wasn't working.

**Comment by PetteriM1** [comment]
Can you send the full server log?

**Comment by SilentBlade1472** [comment]
I will try next time I trigger it again.
